spring:
  application:
    name: sharding-demo
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  #    url: jdbc:mysql://127.0.0.1:33308/sharding_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33308/sharding_demo
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
